version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/gebv/goapp_example
    steps:
      - checkout
      # - run:
      #     name: Update env
      #     command: |
      #       echo 'export PATH="$GOPATH/bin:$PATH"' >> $BASH_ENV
      #       echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      #       source $BASH_ENV
      # - run:
      #     name: Run tests
      #     command: |
      #       make test ## TODO: fixed
      - run:
          name: Build application
          command: |
            make build
      - run:
          name: Preparing the artifacts
          command: |
            mkdir -p /tmp/app_bin
            cp -p ~/bin/* /tmp/app_bin
      - store_artifacts:
          path: /tmp/app_bin
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
